import { playlist } from "../data";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  return {
    props: { playlistLists: playlist },
  };
};

export default ({ playlistLists }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music playlist</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <link
          rel="stylesheet"
          href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>S5 Music Playlist</h1>

        <div>
          {playlist.map((playlists) => (
            <>
              <ul class="list pl0 mt0 measure center">
                <a href="" class="f6 link blue hover-dark-gray">
                  <li class="flex items-center lh-copy pa3 ph0-l bb b--white-10">
                    <img
                      class="w2 h2 w3-ns h3-ns br-100"
                      src={playlists.albumCoverUrl}
                      alt={playlists.name}
                    />
                    <div class="pl3 flex-auto">
                      <span class="f6 b db white">{playlists.artist} </span>
                      <span class="f6 db white">{playlists.genre}</span>
                    </div>
                  </li>
                </a>
              </ul>
            </>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>Cruz</span>
      </footer>
    </div>
  );
};
